#!/bin/sh

nome=$1

[ -z "$nome" ] && {
	echo "$0 arquivo (sem extensão)"
	exit 1
}

echo ".c -> .s"
gcc -S -march=i386 -fverbose-asm -O0 $nome.c 

#echo ".s -> .o"
#as $nome.s -o $nome.o

echo ".s -> exe"
gcc $nome.s -o $nome
