# Project: CompilaDOR
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe -D__DEBUG__
CC   = gcc.exe -D__DEBUG__
WINDRES = windres.exe
RES  = 
OBJ  = obj/atomo.o obj/tabid.o obj/compilador.o obj/arquivo.o obj/erro.o obj/lexico.o obj/sintatico.o obj/semantico.o $(RES)
LINKOBJ  = obj/atomo.o obj/tabid.o obj/compilador.o obj/arquivo.o obj/erro.o obj/lexico.o obj/sintatico.o obj/semantico.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  -g3 
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = bin/compilaDOR.exe
CXXFLAGS = $(CXXINCS)   -g3
CFLAGS = $(INCS)   -g3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before bin/compilaDOR.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "bin\compilaDOR.exe" $(LIBS)

obj/atomo.o: ../../Subjects/Compiladores/CompilaDOR/src/atomo.c
	$(CC) -c ../../Subjects/Compiladores/CompilaDOR/src/atomo.c -o obj/atomo.o $(CFLAGS)

obj/tabid.o: ../../Subjects/Compiladores/CompilaDOR/src/tabid.c
	$(CC) -c ../../Subjects/Compiladores/CompilaDOR/src/tabid.c -o obj/tabid.o $(CFLAGS)

obj/compilador.o: ../../Subjects/Compiladores/CompilaDOR/src/compilador.c
	$(CC) -c ../../Subjects/Compiladores/CompilaDOR/src/compilador.c -o obj/compilador.o $(CFLAGS)

obj/arquivo.o: ../../Subjects/Compiladores/CompilaDOR/src/arquivo.c
	$(CC) -c ../../Subjects/Compiladores/CompilaDOR/src/arquivo.c -o obj/arquivo.o $(CFLAGS)

obj/erro.o: ../../Subjects/Compiladores/CompilaDOR/src/erro.c
	$(CC) -c ../../Subjects/Compiladores/CompilaDOR/src/erro.c -o obj/erro.o $(CFLAGS)

obj/lexico.o: ../../Subjects/Compiladores/CompilaDOR/src/lexico.c
	$(CC) -c ../../Subjects/Compiladores/CompilaDOR/src/lexico.c -o obj/lexico.o $(CFLAGS)

obj/sintatico.o: ../../Subjects/Compiladores/CompilaDOR/src/sintatico.c
	$(CC) -c ../../Subjects/Compiladores/CompilaDOR/src/sintatico.c -o obj/sintatico.o $(CFLAGS)

obj/semantico.o: ../../Subjects/Compiladores/CompilaDOR/src/semantico.c
	$(CC) -c ../../Subjects/Compiladores/CompilaDOR/src/semantico.c -o obj/semantico.o $(CFLAGS)
